name: 🐞 Bug
description: File a bug/issue
title: "<title>"
labels: ["bug", "needs triage"]
body:
- type: markdown
  attributes:
    value: |
      Did you know? Rose also has a [Discord channel](https://discord.com/channels/405213567118213121/1073220911106371626) to discuss bugs and issues!
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  id: version
  attributes:
    label: Launcher Version
    description: Please enter the version of the launcher you are using.
  validations:
    required: true
- type: dropdown
  id: os
  attributes:
    label: Operating System
    description: Please select the OS you are using.
    options:
      - Windows
      - Mac
      - Linux
  validations:
    required: true
- type: dropdown
  id: arch
  attributes:
    label: Architecture
    description: Please select the architecture you are using.
    options:
      - x64
      - ARM
      - others (Please specify in the description)
  validations:
    required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false